### ISSUE TITLE
error with RaceStartlist

### ISSUE THREAD

**Issue by jg345** [themm1/procyclingstats#10]
Getting this error when I use RaceStartlist.

`     94         for team_html in startlist_html.css(".ridersCont"):
     95             riders_table = team_html.css_first("ul")
---> 96             table_parser = TableParser(riders_table)
     97             rider_f_to_parse = [f for f in casual_rider_fields if f in fields]
     98             table_parser.parse(rider_f_to_parse)

AttributeError: 'NoneType' object has no attribute 'css_first'`

I see this has come up before, but I am using 0.1.6.

Thanks

**Comment by themm1** [comment]
Could you please provide concrete URL of page where this is happening? I've tried few startlist URLs and everything worked.

**Comment by themm1** [comment]
Could you please provide concrete URL where this is happening? I've tried few startlist URLs and everything was working.
