### ISSUE TITLE
Problem scraping if rider DNF first stage

### ISSUE THREAD

**Issue by colinduplantis** [themm1/procyclingstats#15]
$ python test.py
[
Traceback (most recent call last):
  File "/Users/colin/marketcetera/workspaces/procyclingstats/code/procyclingstats/examples/test.py", line 27, in <module>
    pprint(stage.parse())
  File "/Users/colin/Library/Python/3.10/lib/python/site-packages/procyclingstats/scraper.py", line 112, in parse
    parsed_data[method_name] = method()
  File "/Users/colin/Library/Python/3.10/lib/python/site-packages/procyclingstats/stage_scraper.py", line 298, in results
    table = join_tables(table, table_parser.table, "rider_url")
  File "/Users/colin/Library/Python/3.10/lib/python/site-packages/procyclingstats/utils.py", line 162, in join_tables
    table.append({**table2_dict[row[join_key]], **row})
KeyError: 'rider/laurens-de-plus'

In the first stage of the '23 Vuelta, Laurens de Plus crashed and DNF. Not sure if this is the source of the issue or not. Sample script attached to reproduce.

[test.py.txt](https://github.com/themm1/procyclingstats/files/12499431/test.py.txt)

**Comment by themm1** [comment]
Yes I know about it, I'll try to fix it in next update.

**Comment by colinduplantis** [comment]
Thanks a million!

My Python skills are next to nothing otherwise I would try to help.

**Comment by themm1** [comment]
No problem, it should be quite easy fix :))

**Comment by henryjcee** [comment]
Dug into this a little bit, issue doesn't seem to be the DNF but the fact that times were taken with 9km to go but the finishing positions were taken as normal at the finish line. As a result the time diffs have an artifact for Andrea Piccolo who was leading the race with 9kms to go (and recorded the quickest time for the stage) but finished 39th across the line. 

In the official race results this was reported as him finishing in 39th place with no time gap (0 seconds) and there seems to have been an issue recording this on PCS where his time is recorded as `-1:0-1:0-19`.

<img width="816" alt="Screenshot 2023-12-31 at 09 10 44" src="https://github.com/themm1/procyclingstats/assets/9272958/0e68b14b-2eea-48e8-9821-b211268d60d4">

Have pinged PCS to see what they think but more generally a better fix would probably be drop rows that have parsing errors and log an error every time it happens as there must be data quality issues all over PCS.

**Comment by themm1** [comment]
I fixed the problem by setting the time for every rider, whose time is in invalid format, to the time in previous row. Hope this helps. New version is available on PyPI.
