### ISSUE TITLE
Question about your api

### ISSUE THREAD

**Issue by Wannes-VanPuyvelde** [themm1/procyclingstats#17]
Hi when I use your api how does it work exactly? Does it work like this: 
I use this in my python application: 
>>> from procyclingstats import Rider
>>> rider = Rider("rider/tadej-pogacar")
>>> rider.birthdate()
"1998-9-21"

When does the webscraping happen? Is it scraping locally from my device or am I making calls to a db/server that you created using the scraping? When is the data updated? 

Thanks for your answer

**Comment by themm1** [comment]
When you run the shown script, you make an HTML request to procyclingstats.com. The library then parses retrieved HTML and returns wanted data. So everything is happening locally on your device. Basically the main thing that the library does, is HTML parsing.
