### ISSUE TITLE
Race results

### ISSUE THREAD

**Issue by timdhaeyer** [themm1/procyclingstats#23]
Is it possible to add the results of a race? So parsing the table that you see in for example /race/gp-samyn/2024/result
<img width="593" alt="image" src="https://github.com/themm1/procyclingstats/assets/47555315/8dedb2b5-9943-47c8-9258-9b66927bd4ac">

**Comment by bmserras** [comment]
I believe you can do this using the Stage class, because this is a one day race:

`
results = Stage("race/gp-samyn/2024/result").results()
`

**Comment by timdhaeyer** [comment]
Indeed, that works. Thanks 👍
