### ISSUE TITLE
Results of one day race

### ISSUE THREAD

**Issue by Toto-Africa** [themm1/procyclingstats#26]
Dear themm1, thank you for all the great work you already did on this Procyclingstats scraper.

I was wondering if it is possible to retrieve the results of a certain one day race? In my specific case, I am only interested in obtaining the winner.

I already tried multiple things, such as scraping the url (e.g. `race/paris-roubaix/2024/result`), or try to execute `Race.stage_winners()`. Unfortunately none of these did work.

Do you perhaps know of any method to retrieve the winner of a one day race?

Best regards.

**Comment by themm1** [comment]
Sorry for the delay. You can use ``Stage.results()``. First item in the returned list is the winner of the one day race/stage.
```py
from procyclingstats import Stage

stage = Stage("race/paris-roubaix/2024/result")
print(stage.results()[0])
```
