### ISSUE TITLE
race.stages() throws UnexpectedParsingError

### ISSUE THREAD

**Issue by Pami01** [themm1/procyclingstats#27]
Trying to parse stages from a specific Race, with the code provided by your repo in the file `examples\climbs_by_stages.py`

`RACE_URL = "race/tour-de-france/2022"`
`race = Race(f"{RACE_URL}/overview")`
`race_climbs = RaceClimbs(f"{RACE_URL}/route/climbs")`
`stages = race.stages()`

Throws exception _UnexpectedParsingError_ with error 

> procyclingstats.errors.UnexpectedParsingError: Field 'profile_icon' wasn't parsed correctly

I've gave a watch at the error and it seems that your code can't parse the stages table due to one extra row 'sum' that calculates the sum of all kms stage. I suggest the removal of this row before the TableParsing.

**Comment by kiernanlabs** [comment]
seeing the same issue.  probably easiest to remove it in the same spot that rest days are removed in race_scraper.py
        # remove rest day table rows
        for stage_e in stages_table_html.css("tbody > tr"):
            not_p_icon = stage_e.css_first(".icon.profile.p")
            if not_p_icon:
                stage_e.remove()
