### ISSUE TITLE
climbs() method for Stage scraper produces empty list

### ISSUE THREAD

**Issue by michaeljgallagher** [themm1/procyclingstats#3]
https://github.com/themm1/procyclingstats/blob/14c49218d67f2d9311db4c9da4166dc3232706f3/procyclingstats/stage_scraper.py#L258

Was following along with the [examples/climbs_by_stages.py](https://github.com/themm1/procyclingstats/blob/master/examples/climbs_by_stages.py) example, but all values in the `stages_climbs` dict were empty lists. Found that it was the climbs() method for Stage scraper not grabbing them from their respective pages. I resolved this locally by changing the CSS selector:

```python
climbs_html = self.html.css_first("ul.list.circle") 
```

Worth noting that I installed procyclingstats from pip, and when doing so the version of selectolax that was installed in my virtual environment was 0.3.12, which is different than the version listed in requirements.txt (0.3.8). Not sure if related.

**Comment by themm1** [comment]
Thanks for reporting an issue. Somehow I've put only stages with no climbs to my testing dir., so it didn't catch the error. PCS changed their HTML a little so I had to change the line to `self.html.css_first("ul.list.circle")` .  Now in the latest version it should work as expected. (to get lates version just run `pip install procyclingstats --upgrade`)
