### ISSUE TITLE
team.wins_count() throws a ValueError when the team has no wins

### ISSUE THREAD

**Issue by Cheeseycube** [themm1/procyclingstats#30]
The wins_count() function located in team_scraper.py assumes that the retrieved html text will be a valid integer, but throws an error when there are no wins because procyclingstats.com displays that with a dash instead of a zero. You can see what I mean below.

`return int(wins_count_html.text())`

I will be submitting a pull request with a simple fix if you would like to merge it.

**Comment by themm1** [comment]
Merged.
