### ISSUE TITLE
Feature Request to add "age" method to Rider class

### ISSUE THREAD

**Issue by Cheeseycube** [themm1/procyclingstats#32]
It would be nice to scrape the age from a given rider, rather than having to calculate it after the fact from their birthdate.  To that end I have created a pull request with the addition of an age() method in the Rider class.

**Comment by themm1** [comment]
Sorry, but I am not planning to add this feature. My goal is to do just the HTML parsing of the information from pages and leave the processing of received data to end users. It's quite easy to calculate age of the rider from their's birthdate or it's possible to get rider's age easily during a race with the ``Stage.results`` method for example.
