### ISSUE TITLE
rider_number in Stage.results, points, kom, gc, youth  

### ISSUE THREAD

**Issue by hidde1977** [themm1/procyclingstats#4]
Hi @themm1 , after many years of non coding I am feeling pretty rookie in python, but I have succeeded in writing some code to scrape results (all stage results, for an xlsx driven cycling game I alway play with some 100 friends. Extremely useful to be able to load all results. 

Hoewever, somewhere after the recent giro - all scraping working perfectly during the giro - it appears that the rider_number column has disappeared from the Stage.results, points, kom, gc and youth. Also, startlist seems empty (from the API documentation I read that rider_number should only to be available in Racestartlist.startlist, but is was in results as well. In the html code the BIBs seem to be available in the results pages anyway. 

As a BIB number is much easier and more consistent to match, my excel is driven on the BIB number, not so much the rider_name. A workaround to find the rider_number in Racestartlist.startlist() and put it in the dataframe I need for the results is possible, but not desireable if the data is also available in the results. Can you explain this issue? 
Hoewever, in the html code the BIBs seem to be available in the results pages. 

many thx!!

**Comment by hidde1977** [comment]
in addition, also the race_startlist.startlist() raises an AttributeError ('NoneType' object has no attribute 'css_first'), no data is found where it should be expected

**Comment by themm1** [comment]
Thanks for reporting an issue. I've fixed the startlist parsing method so it should be working correctly now. It's not yet published on PyPI, because they've made quite a lot of changes to their UI and I will have to fix some more bugs probably, but the fixed Startlist.startlist method is on GitHub already.

I'm not sure what do you mean by rider_number column from Stage.results, since it has never been there.

**Comment by themm1** [comment]
Ok, my bad. I understood that it has been available in the method and now it isn't but now when I'm rereading your post I see what you meant. But yeah, I will add this column to the returned tables. I didn't even notice that BIB has been availeble there until now.

**Comment by hidde1977** [comment]
great! hope the update will be there before the tour!

**Comment by themm1** [comment]
New version with this feature available on PyPI. https://github.com/themm1/procyclingstats/releases/tag/pypi-release

**Comment by hidde1977** [comment]
[like]  Hidde Reitsma reacted to your message:
________________________________
