### ISSUE TITLE
race.stages() fails

### ISSUE THREAD

**Issue by xlsrln** [themm1/procyclingstats#5]
Seems like the site has changed. I get the following when using race.stages()

```
AttributeError                            Traceback (most recent call last)

----> 8         race.stages()

in stages(self, *args)

----> 172         if self.is_one_day_race():
    173             return []

in is_one_day_race(self)

     73         one_day_race_html = self.html.css_first("div.sub > span.blue")
---> 74         return "stage" not in one_day_race_html.text().lower()
     75 

AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by hidde1977** [comment]
Seems so indeed, it's a pity. I raised kind of the same issue. @themm1 @baronet2  any thoughts?

**Comment by themm1** [comment]
It should be working now when you fork the current repo. Next time please provide the URL from which you were scraping. (It wasn't a problem now, since it wasn't working on any race overview URL).
