### ISSUE TITLE
startlist() fails

### ISSUE THREAD

**Issue by kiernanlabs** [themm1/procyclingstats#6]
Thanks for all the great work on this!
Happy to help with some MRs when I get time this weekend if you're open to it

Currently the startlist() parse appears broken.  When I run the example code 
`race_startlist = RaceStartlist("race/tour-de-france/2022/startlist")
race_startlist.startlist()`

I get the following error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 race_startlist = RaceStartlist("race/tour-de-france/2022/startlist")
----> 2 race_startlist.startlist()

File [~/racestats/.venv/lib/python3.8/site-packages/procyclingstats/race_startlist_scraper.py:96](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/joey32/racestats/~/racestats/.venv/lib/python3.8/site-packages/procyclingstats/race_startlist_scraper.py:96), in RaceStartlist.startlist(self, *args)
     93 startlist_html = self.html.css_first(".startlist_v3")
     94 # startlist is individual startlist e.g.
     95 # race/tour-de-pologne/2009/gc/startlist
---> 96 if startlist_html.css_first("li.team") is None:
     97     startlist_html = self.html.css_first(".page-content > div")
     98     startlist_table = []

AttributeError: 'NoneType' object has no attribute 'css_first'`

**Comment by kiernanlabs** [comment]
Nevermind, looks like this was fixed with the last commit, thanks!

**Comment by themm1** [comment]
Yeah, sorry I forgot to close the issue. I will have to fix some more bugs and it then the version will be uploaded to PyPI too.
