### ISSUE TITLE
PCI and UCI points in rider results are all 0s

### ISSUE THREAD

**Issue by kiernanlabs** [themm1/procyclingstats#7]
Currently it looks like it is parsing all UCI and PCI points in the rider results as 0s

E.g. 
rider_results = RiderResults("rider/rui-oliveira/results")
rider_results.results()

Shows 0s for the first stage: race/tour-of-slovenia/2023/stage-3
despite earning 4 and 3 points respectively: https://www.procyclingstats.com/rider/rui-oliveira/results

**Comment by kiernanlabs** [comment]
Fixed here: https://github.com/themm1/procyclingstats/pull/8

**Comment by themm1** [comment]
Thanks for reporting and fixing! Merged.
